#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry 'AdvLinuxTU Recovery Mode' {
	recordfail
	load_video
	insmod gzio
	if [ x$grub_platform = xxen ]; then insmod xzio; insmod lzopio; fi
	insmod ext2
	if [ x$grub_platform = xefi ]; then
		insmod part_gpt
		set root='hd0,gpt2'
		if [ x$feature_platform_search_hint = xy ]; then
          		search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt2 --hint-efi=hd0,gpt2 --hint-baremetal=ahci0,gpt2 old-uuid
        	else
          		search --no-floppy --fs-uuid --set=root old-uuid
        fi
	elif [ x$grub_platform = xpc ]; then
		insmod part_msdos
		set root='hd0,msdos2'
	fi
	linux	/boot/vmlinuz file=/advupdate/preseed/xubuntu.seed boot=advupdate uuid=old-uuid only-ubiquity ota rw quiet splash
	initrd	/boot/initrd
}
